services:
  db:
    container_name: picast_db
    image: mysql:8.3.0
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - './docker/db:/var/lib/mysql'
      - './docker/conf/mysql:/etc/mysql/conf.d'
    environment:
      MYSQL_DATABASE: picast
      MYSQL_ROOT_PASSWORD: example
    ports:
      - '3306:3306'

  adminer:
    container_name: picast_adminer
    image: adminer
    ports:
      - '8080:8080'

  web:
    container_name: picast_web
    build:
      context: ./
      dockerfile: docker/web.Dockerfile
    volumes:
      - './:/var/www/html'
      - './docker/php:/usr/local/etc/php/custom.d'
    links:
      - db
      - memcached
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_enable=1
      PHP_IDE_CONFIG: serverName=Docker
      PHP_INI_SCAN_DIR: '/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d'

  nginx:
    container_name: picast_nginx
    image: 'nginx:1.17'
    ports:
      - '80:80'
    volumes:
      - './public:/var/www/html'
      - './docker/nginx/nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - web

  memcached:
    container_name: picast_memcached
    image: 'memcached:latest'

  mailhog:
    container_name: picast_mailhog
    image: mailhog/mailhog
    ports:
      - '1025:1025'
      - '8025:8025'
