name: Publishing
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    #needs: tests

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Composer Install and Migrate up
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          PASSWORD: ${{ secrets.SSH_KEY }}
          script: php -v

      - name: Pull
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          PASSWORD: ${{ secrets.SSH_KEY }}
          script: cd ${{ secrets.PUBLISH_DIR }} && git pull

      - name: Composer Install and Migrate up
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          PASSWORD: ${{ secrets.SSH_KEY }}
          script: cd ${{ secrets.PUBLISH_DIR }} && composer install --no-dev && php artisan migrate --force
