# GitHub Action for Laravel with MySQL and Redis
name: Testing Laravel with MySQL
on:
  push:
    branches:
      - master
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Startup
        run: docker-compose up -d --remove-orphans

      - name: Sleep
        uses: jakejarvis/wait-action@master
        with:
          time: '60s'

      - name: Check docker container
        run: docker ps

      - name: Env file
        run: mv .env.example .env

      - name: Composer Install
        run: docker exec  picast_web sh -c "composer install"

      - name: Migrate up
        run: docker exec  picast_web sh -c "php artisan migrate"

      - name: Test
        run: vendor/bin/phpunit


  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: tests

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pull
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSH_KEY }}
          script: cd ${{ secrets.PUBLISH_DIR }} && git pull

      - name: Composer Install and Migrate up
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
            PORT: ${{ secrets.PORT }}
            KEY: ${{ secrets.SSH_KEY }}
            script: cd ${{ secrets.PUBLISH_DIR }} && composer install && php artisan migrate