name: Publishing
on:
  push:
    branches:
      - master
jobs:
  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
        with:
          php-version: '8.3'
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: composer install
      - name: PHPStan
        run: vendor/bin/phpstan analyse
      - name: Pint
        run: vendor/bin/pint --test
  tests:
    name: Tests
    runs-on: ubuntu-latest
    services:
      mysql-service:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: example
          MYSQL_DATABASE: db_test
        ports:
          - 33306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
        with:
          php-version: '8.3'
          extensions: gd
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: composer install
      - name: Create database
        run: php artisan app:create-database db_test --env=github
      - name: Migrate
        run: php artisan migrate --env=github
      - name: Seed
        run: php artisan db:seed YouTubeVideoStatusSeeder --env=github
      - name: Run test
        run: php artisan test --env=github

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [ lints,tests ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check PHP version
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          PASSWORD: ${{ secrets.SSH_KEY }}
          script: cd ${{ secrets.PUBLISH_DIR }} && pwd && whereis php && /opt/php83/bin/php -v

      - name: Pull
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          PASSWORD: ${{ secrets.SSH_KEY }}
          script: cd ${{ secrets.PUBLISH_DIR }} && git pull

      - name: Composer Install
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          PASSWORD: ${{ secrets.SSH_KEY }}
          script: cd ${{ secrets.PUBLISH_DIR }} && composer install --no-dev

      - name: Migrate up
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          PASSWORD: ${{ secrets.SSH_KEY }}
          script: cd ${{ secrets.PUBLISH_DIR }} && php artisan migrate --force

      - name: Db seed
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          PASSWORD: ${{ secrets.SSH_KEY }}
          script: cd ${{ secrets.PUBLISH_DIR }} && php artisan db:seed

      - name: Stop worker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          PASSWORD: ${{ secrets.SSH_KEY }}
          script: cd ${{ secrets.PUBLISH_DIR }} && php artisan queue:restart

#      - name: Run worker
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          USERNAME: ${{ secrets.USERNAME }}
#          PORT: ${{ secrets.PORT }}
#          PASSWORD: ${{ secrets.SSH_KEY }}
#          command_timeout: "30s"
#          script: |
#            cd ${{ secrets.PUBLISH_DIR }}
#            nohup php artisan queue:work --daemon >> storage/logs/nohup-worker.log &
#            exit
