name: Publishing
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    #needs: tests

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check PHP version
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          PASSWORD: ${{ secrets.SSH_KEY }}
          script: cd ${{ secrets.PUBLISH_DIR }} && pwd && whereis php && /opt/php83/bin/php -v

      - name: Pull
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          PASSWORD: ${{ secrets.SSH_KEY }}
          script: cd ${{ secrets.PUBLISH_DIR }} && git pull

      - name: Composer Install
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          PASSWORD: ${{ secrets.SSH_KEY }}
          script: cd ${{ secrets.PUBLISH_DIR }} && composer install --no-dev

      - name: Migrate up
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          PASSWORD: ${{ secrets.SSH_KEY }}
          script: cd ${{ secrets.PUBLISH_DIR }} && php artisan migrate --force

      - name: Stop worker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          PASSWORD: ${{ secrets.SSH_KEY }}
          script: cd ${{ secrets.PUBLISH_DIR }} && php artisan queue:restart

      - name: Run worker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          PASSWORD: ${{ secrets.SSH_KEY }}
          script: cd ${{ secrets.PUBLISH_DIR }} && nohup php artisan queue:work --daemon >> storage/logs/nohup-worker.log & | exit
